### ISSUE TITLE
Missing links for schema:subEvent or missing more granular classification of events.

### ISSUE THREAD

**Issue by splattater** [AKSW/leipzig.dataweek.de#26]
The site.nt used for 2022 uses `schema:subEvent` in different ways.
Here an example for the scads event:
https://github.com/AKSW/leipzig.dataweek.de/blob/d2f78f2563662e5f19f27a39c36f9530ffa6f4a6/site.nt#L1060-L1084

and a session-iri of the same event:
https://github.com/AKSW/leipzig.dataweek.de/blob/d2f78f2563662e5f19f27a39c36f9530ffa6f4a6/site.nt#L932-L940

Since the session does not link to the talks, we only can distinguish between sessions and talks with string operators.

A positive example is.
https://github.com/AKSW/leipzig.dataweek.de/blob/d2f78f2563662e5f19f27a39c36f9530ffa6f4a6/site.nt#L1116-L1126

Solution:

The rdf pipeline should (a) add a `rdf:type`-stastement to talks and session events and/or (b) avoid the usage of flat subevents as shown in <https://2022.dataweek.de/bdib-22/>

**Comment by white-gecko** [comment]
I don't fully understand what your issue is. You can see the usage of subevents in the last years templates. The origin of the modeling are (1) the terms provided by schema.org (https://schema.org/Event) and (2) the way how the events are actually organized. This is shown in the table of the event organization.

**Comment by white-gecko** [comment]
Not relevant anymore
